# Generated by Django 3.2 on 2022-07-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('white', 'White')], db_index=True, max_length=15, null=True)),
                ('size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], db_index=True, max_length=3, null=True)),
                ('capacity', models.CharField(blank=True, choices=[('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB')], db_index=True, max_length=15, null=True)),
                ('catagory', models.ManyToManyField(related_name='variant', to='product.Category')),
            ],
        ),
    ]
