# Generated by Django 3.2 on 2022-07-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prouduct_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='product.productdiscount'),
        ),
    ]
