# Generated by Django 3.2 on 2022-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productvariant_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='variant',
            field=models.ManyToManyField(related_name='category', to='product.ProductVariant'),
        ),
    ]
