# Generated by Django 3.2 on 2022-07-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='variant',
        ),
    ]
