# Generated by Django 3.2 on 2022-07-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prouduct_discount',
            new_name='product_discount',
        ),
    ]
